apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Zeus-3x/homelab.git
    targetRevision: main
    path: infrastructure/flannel
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-flannel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
