apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-vars.yaml
  - flannel.yaml
  - metallb.yaml
  - metallb-config.yaml
  - traefik.yaml
  - argocd-ingress.yaml
  - longhorn.yaml
  - longhorn-ingress.yaml
  - signoz.yaml
  - signoz-ingress.yaml
